# Inspired by
# https://github.com/guix-science/guix-science/blob/master/.github/workflows/build.yml
# and
# https://github.com/PromyLOPh/guix-install-action

name: Releases

on:
  push:
    tags: '*'
    ## To test, uncomment the line below with branch name used for review.
    branches: [ fix-flatpak ]

jobs:
  build-binaries:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl]
        # See https://github.com/actions/virtual-environments
        # for the list of official distributions.
        os: [ubuntu-20.04]
      # fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:

    # Check out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git-core flatpak-builder

    - name: Build Flatpak
      shell: bash
      # Don't run scripts with `sudo` since it would use /root as home instead
      # of the runner's /home/runner.
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install --noninteractive org.gnome.Sdk/x86_64/44
        make flatpak-repository
        make flatpak-bundle

    - name: Generate release notes
      shell: bash
      run: |
        echo "Release notes: https://nyxt.atlas.engineer/article/release.org" >> release.txt
        echo "" >> release.txt
        echo "To compile from source, prefer the tarball including the submodules if you don't manage the Lisp dependencies yourself." >> release.txt

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: release.txt
        artifacts: "*.flatpak"
